### ISSUE TITLE
Désactivation de modules

### ISSUE THREAD

**Issue by Lgt2x** [TCastus/ASTUSbot#42]
Donner la possibilité de pouvoir désactiver des modules en commentant seulement le chargement via load_extension. Par exemple, pour lancer le bot sans la commande TGG (pour ne pas avoir à générer de token), il faut aussi commenter plusieurs lignes dans cog.py en plus de commenter la ligne d'activation du module.

Deuxième solution, éviter le crash quand le token Google est celui par défaut

**Comment by Azmah-Bad** [comment]
oui, ce que je fais c'est de commenter ca puis ca marche 
```
# bot.load_extension("cogs.tgg.cog")    dans main 
# from .cog import CogTGG               dans /cogs/tgg/__init__.py
```

**Comment by titouan-joseph** [comment]
Oui my bad, je ne l'ai pas mis dans le`` __init__`` de la class
je changerai ca 😊
